## Setup and Load Data


In [1]:
import pandas as pd

df = pd.read_csv("fake_or_real_news.csv")

In [2]:
df.head()

Unnamed: 0  ... label
0        8476  ...  FAKE
1       10294  ...  FAKE
2        3608  ...  REAL
3       10142  ...  FAKE
4         875  ...  REAL

[5 rows x 4 columns]

## Data Preprocessing

In [3]:
from sklearn.model_selection import train_test_split

X = df.text
y = df.label
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.33, random_state=53)

### Build Bag of Words Vector with CountVectorizer

In [4]:
from sklearn.feature_extraction.text import CountVectorizer

count_vectorizer = CountVectorizer(stop_words="english")

count_train = count_vectorizer.fit_transform(X_train.values)
count_test = count_vectorizer.transform(X_test.values)

# getting the names of the features
print(count_vectorizer.get_feature_names()[:10])

['00', '000', '0000', '00000031', '000035', '00006', '0001', '0001pt', '000ft', '000km']


### Building Bag of Words Vector with TF-IDF Vectorizer

In [5]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_vectorizer = CountVectorizer(stop_words="english", max_df=10)

tfidf_train = tfidf_vectorizer.fit_transform(X_train.values)
tfidf_test = tfidf_vectorizer.transform(X_test.values)

# getting the names of the features
print(tfidf_vectorizer.get_feature_names()[:10])

# having a look at the features of the training data
tfidf_train.A[:50]

['0000', '00000031', '000035', '00006', '0001', '0001pt', '000ft', '000km', '001', '0011']


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

### Inspecting the Vectors


In [6]:
count_df = pd.DataFrame(count_train.A, columns=count_vectorizer.get_feature_names())

count_df.head()

00  000  0000  00000031  000035  00006  ...  ما  محاولات  من  هذا  والمرضى  ยงade
0   0    0     0         0       0      0  ...   0        0   0    0        0      0
1   0    0     0         0       0      0  ...   0        0   0    0        0      0
2   0    0     0         0       0      0  ...   0        0   0    0        0      0
3   0    0     0         0       0      0  ...   0        0   0    0        0      0
4   0    0     0         0       0      0  ...   0        0   0    0        0      0

[5 rows x 56922 columns]

In [7]:
tfidf_df = pd.DataFrame(tfidf_train.A, columns=tfidf_vectorizer.get_feature_names())

tfidf_df.head()

0000  00000031  000035  00006  0001  ...  محاولات  من  هذا  والمرضى  ยงade
0     0         0       0      0     0  ...        0   0    0        0      0
1     0         0       0      0     0  ...        0   0    0        0      0
2     0         0       0      0     0  ...        0   0    0        0      0
3     0         0       0      0     0  ...        0   0    0        0      0
4     0         0       0      0     0  ...        0   0    0        0      0

[5 rows x 44708 columns]

In [8]:
# Check maybe they are equal
count_df.equals(tfidf_df)

False

## Training and Testing the Naive Bayes Classification Model

### Training and Testing with the Word Counts Vector

In [15]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, confusion_matrix

nb_classifier = MultinomialNB()
nb_classifier.fit(count_train, y_train)
pred = nb_classifier.predict(count_test)
print("Accuracy score: ", accuracy_score(y_test, pred))
confusion_matrix(y_test, pred, labels=['FAKE', 'REAL'])

Accuracy score:  0.893352462936394


array([[ 865,  143],
       [  80, 1003]])

### Training and testing with tf-idf vectors

In [16]:
nb_classifier = MultinomialNB()
nb_classifier.fit(tfidf_train, y_train)
pred = nb_classifier.predict(tfidf_test)
print("Accuracy score: ", accuracy_score(y_test, pred))
confusion_matrix(y_test, pred, labels=['FAKE', 'REAL'])

Accuracy score:  0.8015303682448589


array([[769, 239],
       [176, 907]])

### Improving the Model

In [18]:
import numpy as np

alphas = np.arange(0, 1, 0.1)

def fit_and_predict(alpha):
    nb_classifier = MultinomialNB(alpha=alpha)
    nb_classifier.fit(tfidf_train, y_train)
    pred = nb_classifier.predict(tfidf_test)
    return ("Accuracy score: ", accuracy_score(y_test, pred))

In [19]:
for alpha in alphas:
    score = fit_and_predict(alpha)
    print(alpha)
    print(score)
    print()

/usr/local/lib/python3.6/dist-packages/sklearn/naive_bayes.py:507: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10
  'setting alpha = %.1e' % _ALPHA_MIN)


0.0
('Accuracy score: ', 0.7929220468675275)

0.1
('Accuracy score: ', 0.8101386896221904)

0.2
('Accuracy score: ', 0.8077474892395983)

0.30000000000000004
('Accuracy score: ', 0.8091822094691535)

0.4
('Accuracy score: ', 0.806312769010043)

0.5
('Accuracy score: ', 0.8053562888570062)

0.6000000000000001
('Accuracy score: ', 0.8034433285509326)

0.7000000000000001
('Accuracy score: ', 0.8020086083213773)

0.8
('Accuracy score: ', 0.8020086083213773)

0.9
('Accuracy score: ', 0.8010521281683405)

